ci: debug and test
#8

diff --git a/.github/workflows/development-gate.yml b/.github/workflows/development-gate.yml
--- a/.github/workflows/development-gate.yml
+++ b/.github/workflows/development-gate.yml
@@ -32,6 +32,16 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgtk-3-dev
 
+      - name: Set PKG_CONFIG_PATH
+        if: matrix.platform == 'ubuntu-24.04'
+        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
+
+      - name: Debug PKG-CONFIG
+        if: matrix.platform == 'ubuntu-24.04'
+        run: |
+          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
+          pkg-config --libs gdk-3.0 || echo "GDK-3.0 not found"
+
       - name: Checkout code
         uses: actions/checkout@v4
 
