ci: debug and test
#8

diff --git a/.github/workflows/development-gate.yml b/.github/workflows/development-gate.yml
--- a/.github/workflows/development-gate.yml
+++ b/.github/workflows/development-gate.yml
@@ -27,20 +27,20 @@ jobs:
       APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
     steps:
       - name: Install dependencies (ubuntu only)
-        if: matrix.platform == 'ubuntu-24.04'
+        if: matrix.platform == 'ubuntu-22.04'
         run: |
           sudo apt-get update
-          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgtk-3-dev
+          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
 
-      - name: Set PKG_CONFIG_PATH
-        if: matrix.platform == 'ubuntu-24.04'
-        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
-
-      - name: Debug PKG-CONFIG
-        if: matrix.platform == 'ubuntu-24.04'
-        run: |
-          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
-          pkg-config --libs gdk-3.0 || echo "GDK-3.0 not found"
+#      - name: Set PKG_CONFIG_PATH
+#        if: matrix.platform == 'ubuntu-24.04'
+#        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig" >> $GITHUB_ENV
+#
+#      - name: Debug PKG-CONFIG
+#        if: matrix.platform == 'ubuntu-24.04'
+#        run: |
+#          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
+#          pkg-config --libs gdk-3.0 || echo "GDK-3.0 not found"
 
       - name: Checkout code
         uses: actions/checkout@v4
